---
inventory:
  plugin: SimpleInventory
  options:
    host_file: "./inventory/hosts.yaml"
    group_file: "./inventory/groups.yaml"
    defaults_file: "./inventory/defaults.yaml"
#Here we specify on how many devices are managed in parallel
runner:
    plugin: threaded
    options:
        num_workers: 1
logging:
    log_file: nornir_new.log
    level: DEBUG