---
rtr1:
    hostname: 192.168.1.23
    platform: 'ios'
    username: 'admin'
    password: 'admin'


rtr2:
    hostname: 192.168.1.172
    platform: 'ios'
    username: 'admin'
    password: 'admin'

rtr3:
    hostname: 192.168.1.25
    platform: 'ios'
    username: 'admin'
    password: 'admin'

